# Generated by Django 4.0.10 on 2025-02-18 11:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0094_merge_0090_merge_20221101_1805_0093_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEventConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_wide', models.BooleanField(default=False)),
                ('action', models.CharField(help_text='The action that triggers the event', max_length=124)),
                ('action_description', models.CharField(help_text='A description of the action', max_length=256)),
                ('handlers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('slack', 'Slack')], max_length=64), default=list, help_text='The handlers that should be called when the event is triggered', size=None)),
                ('handlers_configs', models.JSONField(default=dict, help_text='The configuration for the handlers')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_events', to='orgs.org')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customereventconfig',
            constraint=models.UniqueConstraint(fields=('system_wide', 'org', 'action'), name='unique_action'),
        ),
        migrations.AddConstraint(
            model_name='customereventconfig',
            constraint=models.CheckConstraint(check=models.Q(('system_wide', True), ('org__isnull', False), _connector='OR'), name='system_wide_or_org'),
        ),
    ]
