# Generated by Django 4.0.10 on 2025-02-18 14:38

from django.db import migrations, models

import temba.events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customereventconfig",
            name="method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                    ("DELETE", "DELETE"),
                    ("OPTIONS", "OPTIONS"),
                ],
                default=temba.events.models.HTTPMethod.GET,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customereventconfig",
            name="notification_template",
            field=models.TextField(blank=True, default="", help_text="The template to use for notifications"),
        ),
    ]
