# Generated by Django 4.0.10 on 2023-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0090_merge_20221101_1805"),
        ("orgs", "0093_squashed"),
    ]

    operations = []
