# Generated by Django 4.0.10 on 2025-04-08 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0094_merge_0090_merge_20221101_1805_0093_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="chat_users",
            field=models.ManyToManyField(related_name="org_chat_users", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="user_group",
            field=models.CharField(
                choices=[
                    ("A", "Administrator"),
                    ("E", "Editor"),
                    ("V", "Viewer"),
                    ("T", "Agent"),
                    ("S", "Surveyor"),
                    ("C", "Chat User"),
                ],
                default="V",
                max_length=1,
            ),
        ),
    ]
