# Generated by Django 4.0.10 on 2025-11-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0095_org_chat_users_alter_invitation_user_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="authy_id",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="verification_type",
            field=models.SmallIntegerField(choices=[(0, "Phone"), (1, "Email")], default=0),
        ),
    ]
