# Generated by Django 4.0.10 on 2025-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0096_remove_usersettings_authy_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="verification_type",
            field=models.SmallIntegerField(choices=[(0, "Phone"), (1, "Email"), (2, "TOTP")], default=0),
        ),
    ]
