# Generated by Django 4.0.10 on 2025-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0097_alter_usersettings_verification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="verification_type",
            field=models.SmallIntegerField(
                choices=[(0, "Phone"), (1, "Email"), (2, "TOTP"), (3, "Secret Code")], default=0
            ),
        ),
    ]
