# Generated by Django 4.0.6 on 2024-06-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0094_merge_0090_merge_20221101_1805_0093_squashed'),
        ('orgs', '0101_remove_org_administrators_remove_org_agents_and_more'),
    ]

    operations = [
    ]
