# Generated by Django 4.0.6 on 2024-06-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0102_merge_20240611_1503"),
    ]

    operations = []
