# Generated by Django 3.2.16 on 2023-01-31 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassifierTrainingTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "training_doc",
                    temba.utils.models.JSONField(
                        decoder=temba.utils.json.TembaDecoder, default=list, encoder=temba.utils.json.TembaEncoder
                    ),
                ),
                ("pickled_doc", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("I", "In Progress"),
                            ("R", "Retry"),
                            ("C", "Completed"),
                            ("F", "Failed"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "messages",
                    temba.utils.models.JSONField(
                        decoder=temba.utils.json.TembaDecoder, default=dict, encoder=temba.utils.json.TembaEncoder
                    ),
                ),
                (
                    "languages",
                    temba.utils.models.JSONField(
                        decoder=temba.utils.json.TembaDecoder, default=list, encoder=temba.utils.json.TembaEncoder
                    ),
                ),
                ("start_index", models.IntegerField(default=0)),
                ("total_intents", models.PositiveSmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "classifier",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="classifiers.classifier"),
                ),
            ],
        ),
    ]
