# Generated by Django 4.0.10 on 2023-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classifiers", "0006_auto_20230207_1410"),
        ("classifiers", "0007_squashed"),
    ]

    operations = []
