# Generated by Django 4.0.6 on 2024-06-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0009_classifier_is_system'),
        ('classifiers', '0010_classifierduplicateschecktask'),
    ]

    operations = [
    ]
