# Generated by Django 2.2.27 on 2022-02-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0039_merge_20201214_1542"),
    ]

    operations = []
