# Generated by Django 3.2.16 on 2023-01-21 08:58

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0042_alter_campaignevent_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.TranslatableField(max_length=640, null=True),
        ),
    ]
