# Generated by Django 4.0.10 on 2023-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0042_alter_campaignevent_message"),
        ("campaigns", "0045_squashed"),
    ]

    operations = []
