# Generated by Django 4.0.10 on 2024-10-30 07:40

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0046_merge_0042_alter_campaignevent_message_0045_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='message',
            field=temba.utils.models.TranslatableField(max_length=640, null=True),
        ),
    ]
