# Generated by Django 4.0.6 on 2024-06-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0046_merge_0042_alter_campaignevent_message_0045_squashed"),
        ("campaigns", "0048_campaign_is_system"),
    ]

    operations = []
