# Generated by Django 3.2.16 on 2022-11-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0133_auto_20220322_1447"),
        ("channels", "0135_alter_channellog_created_on"),
    ]

    operations = []
