# Generated by Django 4.0.10 on 2024-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0140_smpplog"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelconnection",
            name="answered_by",
            field=models.CharField(choices=[("H", "Human"), ("M", "Machine")], max_length=1, null=True),
        ),
    ]
