# Generated by Django 4.0.6 on 2024-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0139_channel_is_system"),
        ("channels", "0140_smpplog"),
    ]

    operations = []
