# Generated by Django 2.2.27 on 2022-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbeddedBoard",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=256)),
                (
                    "embedding_type",
                    models.CharField(
                        choices=[("P", "Public link to be embedded"), ("M", "Metabase dashboard")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("metabase_dashboard", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
