# Generated by Django 2.2.27 on 2022-09-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0133_auto_20220322_1447"),
        ("msgs", "0159_merge_20220401_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initializing"),
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("U", "En Route"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("H", "Handled"),
                    ("E", "Error Sending"),
                    ("F", "Failed Sending"),
                    ("R", "Resent message"),
                ],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initializing"),
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("U", "En Route"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("H", "Handled"),
                    ("E", "Error Sending"),
                    ("F", "Failed Sending"),
                    ("R", "Resent message"),
                ],
                db_index=True,
                default="P",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="MessageExternalIDMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_created=True, blank=True, help_text="When this item was originally created"
                    ),
                ),
                ("carrier_id", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("gateway_id", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="channels.Channel")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="external_ids", to="msgs.Msg"
                    ),
                ),
            ],
        ),
    ]
