# Generated by Django 2.2.27 on 2022-10-03 11:50

from django.db import migrations, models
import django.db.models.deletion
import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0160_auto_20220919_1809"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageexternalidmap",
            name="request_logs",
            field=temba.utils.models.JSONField(blank=True, encoder=temba.utils.json.TembaEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="messageexternalidmap",
            name="channel",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="channels.Channel"),
        ),
        migrations.AlterField(
            model_name="messageexternalidmap",
            name="message",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="external_ids", to="msgs.Msg"
            ),
        ),
    ]
