# Generated by Django 3.2.16 on 2022-11-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0161_auto_20221003_1150"),
    ]

    operations = []
