# Generated by Django 3.2.16 on 2023-01-12 01:44

import django.db.models.deletion
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0163_alter_msg_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=temba.utils.models.TranslatableField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="ticket",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="broadcasts", to="tickets.ticket"
            ),
        ),
    ]
