# Generated by Django 3.2.16 on 2023-01-27 18:00

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0164_auto_20230112_0144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=temba.utils.models.TranslatableField(max_length=640),
        ),
    ]
