# Generated by Django 4.0.10 on 2023-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0164_auto_20230112_0144"),
        ("msgs", "0169_squashed"),
    ]

    operations = []
