# Generated by Django 4.0.10 on 2023-03-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0170_merge_0164_auto_20230112_0144_0169_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[("I", "Initializing"), ("Q", "Queued"), ("S", "Sent"), ("F", "Failed")],
                default="I",
                max_length=1,
            ),
        ),
    ]
