# Generated by Django 4.0.10 on 2024-10-30 07:40

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0171_alter_broadcast_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=temba.utils.models.TranslatableField(max_length=640),
        ),
    ]
