# Generated by Django 4.0.10 on 2025-03-31 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0154_merge_0145_auto_20221107_1150_0153_squashed'),
        ('orgs', '0094_merge_0090_merge_20221101_1805_0093_squashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0171_alter_broadcast_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_topics', to='orgs.org')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_templates_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_templates', to='orgs.org')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_templates', to='msgs.conversationtopic')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='contacts.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='orgs.org')),
            ],
        ),
    ]
