# Generated by Django 4.0.10 on 2025-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0095_org_chat_users_alter_invitation_user_group"),
        ("msgs", "0172_conversationtemplate_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationtemplate",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="conversationtemplate",
            unique_together={("org", "name")},
        ),
    ]
