# Generated by Django 4.0.10 on 2025-08-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_created_by_to_owners(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Conversation = apps.get_model("msgs", "Conversation")
    ConversationOwner = apps.get_model("msgs", "ConversationOwner")
    owners = []
    for conversation in Conversation.objects.using(db_alias).all():
        owners.append(
            ConversationOwner(
                conversation=conversation,
                owner=conversation.created_by,
            )
        )
    ConversationOwner.objects.using(db_alias).bulk_create(owners)


def copy_owners_to_created_by(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Conversation = apps.get_model("msgs", "Conversation")
    conversations = []
    for conversation in Conversation.objects.using(db_alias).all():
        conversation.created_by = conversation.owners.first()
        conversations.append(conversation)
    Conversation.objects.using(db_alias).bulk_update(conversations, ["created_by"])


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("msgs", "0173_alter_conversationtemplate_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="status",
            field=models.CharField(choices=[("ACT", "Active"), ("ARC", "Archived")], default="ACT", max_length=3),
        ),
        migrations.CreateModel(
            name="ConversationOwner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_read", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="conversationowner",
            name="conversation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="msgs.conversation"),
        ),
        migrations.AddField(
            model_name="conversationowner",
            name="owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="owners",
            field=models.ManyToManyField(
                related_name="conversations_created",
                through="msgs.ConversationOwner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copy_created_by_to_owners, copy_owners_to_created_by),
        migrations.RemoveField(
            model_name="conversation",
            name="created_by",
        ),
    ]
