# Generated by Django 4.2.27 on 2026-04-22 13:29
from functools import reduce

from django.contrib.postgres.aggregates import ArrayAgg
from django.db import migrations, models


def merge_ids(prev: set[int], curr: dict[str, list[int]]) -> set[int]:
    return prev.union(curr["ids"][1:])


def delete_duplicate_conversation_owners(apps, _):
    model = apps.get_model("msgs", "ConversationOwner")
    duplicates = (
        model.objects.values("conversation_id", "owner_id")
        .annotate(
            ids=ArrayAgg("id"),
            duplicate_count=models.Count("id"),
        )
        .filter(duplicate_count__gt=1)
    )
    model.objects.filter(id__in=reduce(merge_ids, duplicates, set())).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0174_conversationowner_remove_conversation_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=delete_duplicate_conversation_owners,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddConstraint(
            model_name="conversationowner",
            constraint=models.UniqueConstraint(fields=("conversation", "owner"), name="unique_conversation_owner"),
        ),
    ]
