# Generated by Django 4.2.27 on 2026-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0174_conversationowner_remove_conversation_created_by_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conversationowner",
            constraint=models.UniqueConstraint(fields=("conversation", "owner"), name="unique_conversation_owner"),
        ),
    ]
