# Generated by Django 4.0.6 on 2024-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0171_alter_broadcast_status'),
        ('msgs', '0175_alter_msg_failed_reason'),
    ]

    operations = [
    ]
