# Generated by Django 4.0.10 on 2024-12-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0282_flowrun_flows_flowrun_events_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudioFlowStart",
        ),
    ]
