# Generated by Django 4.0.6 on 2024-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0281_alter_exportflowimagestask_created_by_and_more'),
        ('flows', '0291_flowrun_flows_run_active_or_waiting_has_session'),
    ]

    operations = [
    ]
