FROM greatnonprofits/ccl-base:v4

RUN apt-get update
RUN apt-get install -y xmlsec1 libxml2 libxmlsec1 libxmlsec1-openssl

RUN wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem \
    -O /usr/local/share/ca-certificates/rds.crt
RUN update-ca-certificates

RUN wget https://ccl-prod.s3.us-west-1.amazonaws.com/phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
RUN ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin

RUN mkdir /rapidpro
WORKDIR /rapidpro

COPY ./pyproject.toml /rapidpro/pyproject.toml
COPY ./poetry.lock /rapidpro/poetry.lock

RUN pip3 install --upgrade pip setuptools
RUN pip3 install -U poetry==1.6.1

RUN poetry export --without-hashes --output pip-freeze.txt

RUN pip3 install -r pip-freeze.txt

COPY . /rapidpro
RUN openssl genrsa -out /rapidpro/certs/sp-key.pem 2048
RUN openssl req -new -x509 -key /rapidpro/certs/sp-key.pem -out /rapidpro/certs/sp-cert.pem -days 3650 -subj "/CN=communityconnectlabs.saml"
COPY docker/docker.settings /rapidpro/temba/settings.py

RUN npm install

RUN rm -f /rapidpro/temba/settings.pyc

COPY docker/entrypoint.sh /
RUN chmod +x /entrypoint.sh

RUN ln -s /usr/bin/python3.9 /usr/bin/python
RUN rm -rf /tmp/* /var/tmp/*[~]$

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]

CMD ["celery"]
