# Generated by Django 3.2.16 on 2022-11-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_linkcontacts_flow"),
        ("notifications", "0005_auto_20211007_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="links_export",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="links.exportlinkstask",
            ),
        ),
    ]
