# Generated by Django 4.0.10 on 2023-03-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_notification_links_export"),
        ("notifications", "0008_squashed"),
    ]

    operations = []
