# Generated by Django 2.2.10 on 2021-01-05 22:47

# import django.db.models.expressions
# import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0129_squashed"),
    ]

    operations = []
