# Generated by Django 4.0.10 on 2023-03-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0145_auto_20221107_1150"),
        ("contacts", "0153_squashed"),
    ]

    operations = []
