# Generated by Django 4.2.27 on 2025-12-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0154_merge_0145_auto_20221107_1150_0153_squashed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contacturn",
            name="non_empty_scheme_and_path",
        ),
        migrations.AddConstraint(
            model_name="contacturn",
            constraint=models.CheckConstraint(
                check=models.Q(("scheme", ""), ("path", ""), _connector="OR", _negated=True),
                name="non_empty_scheme_and_path",
            ),
        ),
    ]
