# Generated by Django 3.2.16 on 2022-11-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0010_merge_20220223_1705"),
        ("request_logs", "0013_auto_20210928_1505"),
    ]

    operations = []
