# Generated by Django 4.0.10 on 2023-03-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0014_merge_20221101_1805"),
        ("request_logs", "0014_squashed"),
    ]

    operations = []
