# Generated by Django 4.0.10 on 2023-03-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0004_squashed"),
        ("sql", "0004_system_label_count"),
    ]

    operations = []
