# Generated by Django 2.2.27 on 2022-09-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0261_flowtemplate_flowtemplategroup"),
        ("links", "0004_remove_link_clicks_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkcontacts",
            name="flow",
            field=models.ForeignKey(
                help_text="The flow related to this link's click",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_flows",
                to="flows.Flow",
            ),
        ),
    ]
