# Generated by Django 2.2.27 on 2022-11-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_linkcontacts_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkcontacts",
            name="flow",
            field=models.ForeignKey(
                help_text="The flow related to this link's click",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_links",
                to="flows.Flow",
            ),
        ),
    ]
