# Generated by Django 3.2.16 on 2022-11-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_linkcontacts_flow"),
        ("links", "0006_auto_20221101_2201"),
    ]

    operations = []
