# Generated by Django 3.2.16 on 2023-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SDoHData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state_code", models.CharField(max_length=2)),
                ("state_name", models.CharField(max_length=64)),
                ("county_code", models.CharField(max_length=3)),
                ("county_name", models.CharField(max_length=64)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
