# Generated by Django 2.2.27 on 2022-02-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0018_merge_20201214_1542"),
    ]

    operations = []
