# Generated by Django 4.0.10 on 2023-03-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0022_merge_20220223_1706"),
        ("triggers", "0023_squashed"),
    ]

    operations = []
