# Generated by Django 4.0.6 on 2024-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0024_alter_trigger_options"),
        ("triggers", "0024_merge_0022_merge_20220223_1706_0023_squashed"),
    ]

    operations = []
