name: OWASP ZAP Scanning
on:
  push:
    branches:
      - main
      - 'dev/5.0'
      - 'feature/owasp-scanning'
jobs:
  zap_scan:
    name: Scan the WEB Application
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://www.zaproxy.org/'